
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/Cellar/cmake/3.26.2/share/cmake/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Darwin - 22.3.0 - arm64
...
